# Generated by Django 3.2.13 on 2022-05-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdustriaEmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreindustria', models.CharField(max_length=30)),
                ('descripcionindustria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'IdustriaEmpresaTitular',
                'verbose_name_plural': 'IdustriaEmpresaTitular',
            },
        ),
    ]
