# Generated by Django 3.2.13 on 2022-05-04 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_idustriaempresatitular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdustriaEmpresaTitular',
            new_name='IndustriaEmpresaTitular',
        ),
    ]
