# Generated by Django 3.2.13 on 2022-05-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empresatitular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresatitular',
            options={'verbose_name': 'Empresa Titular', 'verbose_name_plural': 'Empresa Titular'},
        ),
    ]
