# Generated by Django 3.2.13 on 2022-05-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_empresatitular_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEmpresaTitular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('idempresatitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresatitular')),
            ],
            options={
                'verbose_name': 'Produco Empresa Titular',
                'verbose_name_plural': 'Producto Empresa Titular',
            },
        ),
    ]
