# Generated by Django 3.2.13 on 2022-05-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productoempresatitular'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoriabeneficio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Beneficio',
                'verbose_name_plural': 'Categoria Beneficio',
            },
        ),
        migrations.CreateModel(
            name='EmpresaBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreempresabeneficio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Empresa Beneficio',
                'verbose_name_plural': 'Empresa Beneficio',
            },
        ),
    ]
