# Generated by Django 3.2.13 on 2022-05-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoriabeneficio_empresabeneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTitularBeneficio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebeneficio', models.CharField(max_length=30)),
                ('fechainicio', models.DateField()),
                ('fechatermino', models.DateField()),
                ('checklu', models.BooleanField()),
                ('checkma', models.BooleanField()),
                ('checkmi', models.BooleanField()),
                ('checkju', models.BooleanField()),
                ('checkvi', models.BooleanField()),
                ('checksa', models.BooleanField()),
                ('checkdo', models.BooleanField()),
                ('idcategoriabeneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriabeneficio')),
                ('idempresabeneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresabeneficio')),
                ('idproductoempresatitular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productoempresatitular')),
            ],
            options={
                'verbose_name': 'Empresa Titular Beneficio',
                'verbose_name_plural': 'Empresa Titular Beneficio',
            },
        ),
    ]
