# Generated by Django 3.2.13 on 2022-05-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_empresatitularbeneficio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPreferenciaPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecategoriapreferencia', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria Preferencia Personal',
                'verbose_name_plural': 'Categoria Preferencia Personal',
            },
        ),
    ]
