# Generated by Django 3.2.13 on 2022-05-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuarioproductoempresatitular'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Preferencia',
                'verbose_name_plural': 'Usuario Preferencia',
            },
        ),
    ]
