# Generated by Django 3.2.13 on 2022-05-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuariopreferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPreferencia',
        ),
    ]
