# Generated by Django 3.2.13 on 2022-05-05 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_usuariopreferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='core.preferenciapersonal', to_field='nombrepreferenciapersonal', unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.usuario', to_field='username', unique=True)),
            ],
            options={
                'verbose_name': 'Usuario Preferencia',
                'verbose_name_plural': 'Usuario Preferencia',
            },
        ),
    ]
