# Generated by Django 3.2.13 on 2022-05-05 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_usuarioproductoempresatitular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciapersonal',
            name='nombrepreferenciapersonal',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UsuarioPreferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preferencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='core.preferenciapersonal', to_field='nombrepreferenciapersonal')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.usuario', to_field='username')),
            ],
            options={
                'verbose_name': 'Usuario Preferencia',
                'verbose_name_plural': 'Usuario Preferencia',
            },
        ),
    ]
